### ISSUE TITLE
Reset Modem WAN(Public IP)

### ISSUE THREAD

**Issue by etempm** [pearlxcore/HuaweiAPI#1]
Hi,
very usefull library, thanks for this. I am successfully switching mobile data using "dataswitch" method, but Public/wan ip is not changing. Only when modem resetted, public ip is changing. Do you have idea? is there other method to do reset public ip?
thanks again.

**Comment by pearlxcore** [comment]
Sorry but I no longer use any Huawei devices. But for public IP only can be changed if you reset the device.
