### ISSUE TITLE
Issue with the login process

### ISSUE THREAD

**Issue by matthieupetite** [pearlxcore/HuaweiAPI#4]
Hello, 

I am currently using your library in a side project and I have some issues when trying to build my services. My use case is to send an sms every 15 minutes. Everything work fine in the firt iteration of my loop but for the second try I have an error. Can you please tell me where you found the spec of the Huawei protocol so I will be able to troubleshot the case. I suspect an issue with the session token :(

**Comment by pearlxcore** [comment]
Hi, you can use [this](https://github.com/pearlxcore/Huawei-Router-Tool) as reference for the login process. I don't have any documentation of the api.
